export type ProfileTemplate = {
  id: string;
  name: string;
  description: string;
  theme: string;
  font: string;
  animation: string;
  usernameTheme: string;
};

export const profileTemplates: ProfileTemplate[] = [
  {
    id: "creator-neon",
    name: "Creator Neon",
    description: "Bright and energetic style for creators and streamers.",
    theme: "aurora",
    font: "poppins",
    animation: "fade-up",
    usernameTheme: "gradient-3",
  },
  {
    id: "minimal-pro",
    name: "Minimal Pro",
    description: "Clean and professional look for personal brands.",
    theme: "classic-white",
    font: "inter",
    animation: "none",
    usernameTheme: "indigo",
  },
  {
    id: "dark-spotlight",
    name: "Dark Spotlight",
    description: "Dark contrast style for music, art, and nightlife brands.",
    theme: "twilight",
    font: "space",
    animation: "slide-up",
    usernameTheme: "gradient-1",
  },
  {
    id: "sunrise-vibes",
    name: "Sunrise Vibes",
    description: "Warm gradient profile style for lifestyle creators.",
    theme: "sunset-glow",
    font: "quicksand",
    animation: "fade",
    usernameTheme: "orange",
  },
  {
    id: "blue-wave",
    name: "Blue Wave",
    description: "Fresh cool tones for tech and product makers.",
    theme: "ocean-breeze",
    font: "inter",
    animation: "slide-right",
    usernameTheme: "blue",
  },
  {
    id: "purple-dream",
    name: "Purple Dream",
    description: "Bold purple gradient with energetic transitions.",
    theme: "purple-haze",
    font: "poppins",
    animation: "zoom-in",
    usernameTheme: "violet",
  },
  {
    id: "golden-hour",
    name: "Golden Hour",
    description: "Bright warm look for personal and travel pages.",
    theme: "morning-sky",
    font: "delius",
    animation: "fade-up",
    usernameTheme: "gold",
  },
  {
    id: "emerald-flow",
    name: "Emerald Flow",
    description: "Modern green-blue palette with calm personality.",
    theme: "electric-blue",
    font: "inter",
    animation: "slide-left",
    usernameTheme: "teal",
  },
  {
    id: "pink-pop",
    name: "Pink Pop",
    description: "Fun social style with vibrant pink accents.",
    theme: "pink-sunset",
    font: "borel",
    animation: "pulse",
    usernameTheme: "pink",
  },
  {
    id: "mint-creator",
    name: "Mint Creator",
    description: "Light mint style perfect for creators and coaches.",
    theme: "mint-breeze",
    font: "poppins",
    animation: "float",
    usernameTheme: "green",
  },
  {
    id: "fire-ice-pro",
    name: "Fire & Ice Pro",
    description: "High contrast design to make links stand out.",
    theme: "fire-and-ice",
    font: "space",
    animation: "tada",
    usernameTheme: "gradient-2",
  },
  {
    id: "dark-minimal",
    name: "Dark Minimal",
    description: "Simple dark profile with subtle motion.",
    theme: "dark-mode",
    font: "inter",
    animation: "fade",
    usernameTheme: "default",
  },
  {
    id: "ocean-solid",
    name: "Ocean Solid",
    description: "Reliable blue style for business and portfolio pages.",
    theme: "ocean-blue",
    font: "inter",
    animation: "slide-down",
    usernameTheme: "cyan",
  },
  {
    id: "forest-brand",
    name: "Forest Brand",
    description: "Natural earthy look for wellness and eco brands.",
    theme: "forest-green",
    font: "quicksand",
    animation: "fade-left",
    usernameTheme: "lime",
  },
  {
    id: "sunset-brand",
    name: "Sunset Brand",
    description: "Warm sunset tones for product and campaign launches.",
    theme: "sunset-orange",
    font: "amarna",
    animation: "bounce",
    usernameTheme: "yellow",
  },
  {
    id: "soft-social",
    name: "Soft Social",
    description: "Gentle pastel style for personal bio pages.",
    theme: "soft-pink",
    font: "delius",
    animation: "fade-right",
    usernameTheme: "red",
  },
  {
    id: "neon-punch",
    name: "Neon Punch",
    description: "High-energy neon setup for gaming and streaming.",
    theme: "neon-green",
    font: "space",
    animation: "flash",
    usernameTheme: "indigo",
  },
  {
    id: "royal-brand",
    name: "Royal Brand",
    description: "Elegant purple profile for premium personal brands.",
    theme: "royal-purple",
    font: "poppins",
    animation: "zoom-rotate",
    usernameTheme: "gradient-4",
  },
  {
    id: "sunny-creator",
    name: "Sunny Creator",
    description: "Bright and cheerful look for content creators.",
    theme: "sunny-yellow",
    font: "borel",
    animation: "wiggle",
    usernameTheme: "orange",
  },
  {
    id: "graphite-pro",
    name: "Graphite Pro",
    description: "Professional dark gray profile with clean hierarchy.",
    theme: "deep-gray",
    font: "inter",
    animation: "none",
    usernameTheme: "gradient-5",
  },
  {
    id: "twilight-studio",
    name: "Twilight Studio",
    description: "Creative studio style with cinematic dark gradient.",
    theme: "twilight",
    font: "iceland",
    animation: "spin",
    usernameTheme: "gradient-1",
  },
  {
    id: "aurora-lite",
    name: "Aurora Lite",
    description: "Colorful modern style with smooth transitions.",
    theme: "aurora",
    font: "quicksand",
    animation: "spring",
    usernameTheme: "gradient-3",
  },
];